version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1

  web1:
    image: node:18-alpine
    container_name: web1
    expose:
      - "80"
    environment:
      - NODE_ENV=production
    # Otros ajustes específicos para tu contenedor web1
    volumes:
      - ./web1:/server
    command: /bin/sh -c "cd server && npm start" 
    # Otros ajustes específicos para tu contenedor web2
